spring:
  cloud:
    config:
      enabled: false  
    discovery:
      enabled: false  

management:
  endpoints:
    enabled-by-default: false

springdoc:
  title: Member API Document
  version: 1.0.0
