version: "3"

services:
  member_db:
    image: mariadb:latest
    hostname: member_db
    container_name: member_db
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=board
    ports:
      - 3306:3306
    volumes:
      - ./conf:/etc/mysql/conf.d
      - ./member_db:/var/lib/mysql

networks:
  default:
    name: board_mariadb_net
    external: true
