server:
  port: 8888

spring:
  application:
    name: config-server
  profiles: 
    active: 
#    - native
    - git
  cloud:
    config:
      server:
        native:
          search-locations:  file:../board-configs
        git: 
          uri: https://github.com/KIM-JONG-YOUNG/board
          search-paths: board-configs     # Folder 명
          default-label: master           # Branch 정보
          delete-untracked-branches: true # Remote Repository만 사용

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${server.port}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka