server:
  port: 8001

springdoc:
  title: Member API Document
  version: 1.0.0

spring:
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/board
      username: root
      password: root

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${server.port}}
