server:
  port: 8001

springdoc:
  title: Member API Document
  version: 1.0.0

spring:
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://127.0.0.1:3306/board
      username: root
      password: root
  sql:
    init:
      mode: always
      schema-locations:
      - classpath:member-schema.sql
      data-locations:
      - classpath:member-data.sql

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    